### ISSUE TITLE
Error:  libffi-72499c49.so.6.0.4: cannot open shared object file

### ISSUE THREAD

**Issue by jay1ram2** [snowflakedb/examples#4] opened 2017-01-07 23:52 UTC
The lambda function packaged using "package-lambda-function.sh" threw "Unable to import module 'lambda_function': libffi-72499c49.so.6.0.4: cannot open shared object file: No such file or directory" error. 
 
I solved the issue by changing the command **zip -r9 $DIR/lambda_function.zip \***  to **zip -r9 $DIR/lambda_function.zip .**  

i.e. use '.' instead of '*'

The problem is discussed here: http://stackoverflow.com/questions/38963857/import-error-from-cyptography-hazmat-bindings-constant-time-import-lib
 
Please update your code accordingly.

**Comment by smtakeda** [comment] 2017-02-06 07:01
Just merged the pull request #3

**Closed** 2017-02-06 07:02 UTC

**Comment by gene1wood** [comment] 2018-02-02 22:45
Specifically the file `.libs_cffi_backend` matches when you use `.` but does not match when you use `*`

**Comment by smtakeda** [comment] 2018-02-02 22:48
The fix was in, though, do you still have an issue?

**Comment by gene1wood** [comment] 2018-02-02 22:57
@smtakeda No, I just encountered this exact problem elsewhere (not related to `snowflakedb`) and this issue showed me the cause of the problem. I thought I'd add a note about the specific missing file that's causing the error reported in this issue, `.libs_cffi_backend` in case anyone else finds this issue with the same error message.

**Comment by smtakeda** [comment] 2018-02-02 23:39
Sounds good!
